apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-gui
  namespace: truenas-gui
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 16.11.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: nas.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
          homepage:
            description: Truenas Scale admin panel
            enabled: true
            group: Utilities
            name: Truenas Scale
          nginx:
            enabled: true
    service:
      main:
        enabled: true
        externalIP: ${TRUENAS_IP}
        ports:
          main:
            enabled: true
            port: 81
            protocol: http
        type: ExternalIP
