apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TkCFnskToKvHWafccYfcGmUyFPvkDOZNyhJHw6LRzLN8VequGaRyfA==,iv:/KV/xXtfXbqhTsCKd4ViRxkDGcOysO9UDmzl+VJd838=,tag:Z7ZRr3D1r7cVv67FGgXGRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MG9NVS84Qm5sMlhvRTdP
            eUhYSi9SajRqS2k5c0IzSzlBQ0MyeEJJRW5rCkt5a2F2QjF6UzNuMy9GNlNvaGx0
            eFY2dnU1NzN0MVlTOTJ6c3kzMzZlbDQKLS0tIG90azZrdkFLeHZKK0VRd3FMcXRi
            Y0E4ajUxOTZlS2s1NlhKS3lGSWE3ZEEKPayiyW5jY/VK+o2JSmp/dzpPFs5ULp90
            NSf46wRY/FWzSsOASLF1ECgOtJdNfNJtzp7SyxD0zqHl+aU9q33pIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-08T17:12:40Z"
    mac: ENC[AES256_GCM,data:ckN5cm68qWClpXDJ4KaId4zwGuSU3oaP+qF21J8pY1W1hXxTuA7cg0AQJrazFXXm/HmuwlsJsiXjQPDJGp9GGSa0cnYUzZ9+iJlr/8YXQVhBaRHqcbKaiQJotVOegt1N99LR/tSSEPSF/JN1Gy59OxhmVsarJPreUwL0Whv+iw8=,iv:YujvT9v/rEYxMSNpqMjhUZnXPC7G3l6jAVpaXoRl6BY=,tag:AVpkVD6OaPR7VMGwKC0BSQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
