apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:5yctehmDis5NS4jXbRO0uGXjF398QvQoUMsSAChmRfNYptswxfhY4g==,iv:BLcU8umP/DPv0TGzaTSrxPPvxMZJV1K6snlf4o1YBck=,tag:GcuTqIpz/HDz4A8fn0NLug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQUlvMm83eEFOaEdUQWRv
            NE9SV2VrNWQ4OEZQcUV5c0kyeHFTTUoxcUZRCm0wYlg4Q21QcmN2b1NRT2htMzY5
            aURJVXp3UFhoSlYrN0RQdFlXRjQxc3MKLS0tIEZEZFpndCtUTTU2WnJ5bUZROUNZ
            UjJuT0M2YkZZbFJzV3V4Rk14UlR1TTgKXZoIXBUr3VDTxiNvH6CbOeleyNPpOunZ
            Kg4sPyCTJy8NQ/5HzF+9p5ryK3jCpJMyWSyPznYFQuyTOSrhzgyTWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-07T19:24:25Z"
    mac: ENC[AES256_GCM,data:3jiZSLq+RoqYx2Oyup8vthaFXhAk9C3Ie3lxRKs7bSVADTaS8uCFXf/DfgJc+vuyWPNnWD+QPcRDg948eXHhBte/6JkDJ2IT7yJVKR52H/kU2q8TxqfS14DDlSgrF04L+tVVe/mtxBHBpubNHY6aQB/S/JQzswCkQemc7xZwYKg=,iv:d75v/z1CpNfnh/sH4V2lOlP7dr3FpH3GnKkJ6fKoeHE=,tag:Bz75+bNwmQO9Ad5diyILgA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
