apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:wpwr6PQSAv3JZLbt7nbfpurShB68hizdB+pHWoRUu5GuNNLsUPbpRg==,iv:0Q6olXBBkmeonjN0885VC+yPSyOClYjHKtzEY0XZlmY=,tag:VYfis46/YDQY1tMyUkqWbQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyL2ptZzNlM1BJZDJ4TXdl
            RU9heEZ6b0lENExJZXg2Y1Z6YmtyY1FEZjNrCk9WNFlZbWRickZoQ0N6UUtMOG1q
            andGa0V4VHF3bjJ6NVo0SzY4WDlKRlEKLS0tIEp0L1VSSGxzT3lyOEJhT09kVHRz
            NE5VM2VhRlpncnI4L1ZCbGQ4aVV6OU0KLgioNERpUIH3BbcPQL523J+x8QFCCvtq
            jNgdK4uoEgX/ZNjpBPj4/BCOmFleojp22l2YJGZyLjwfVr2OrM3Okg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T05:02:20Z"
    mac: ENC[AES256_GCM,data:hBhhiBm/Gx3140Cqq4Qeko9c61QiXGpAn0Ye3vigb2gJBvwHy+e2u94zLHhQ+Z3PSIMK3lvroODkYXzXn0mnk5QzAXZ9PTQH44G2LKIpK8PU1UNjwyeBDMfttgvBf7F8LRvq4nTWk2I7iaOCkheqdeMdJ33jFmxSimkuDsYcEck=,iv:vFEp9q6m5WSJr9DWkBr+j6NFW8Ycmz26oJSJPd/FRpU=,tag:g5Wb2aGbsFN1WsKbWtRKsQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
