apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: proxmox-gui
    namespace: proxmox-gui
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 15.5.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        ingress:
            main:
                enabled: true
                hosts:
                    - host: prox.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        description: Proxmox admin panel
                        enabled: true
                        group: Utilities
                        name: Proxmox
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: auth
                              namespace: "traefik"
        service:
            main:
                enabled: true
                externalIP: 192.168.1.241
                ports:
                    main:
                        enabled: true
                        port: 8006
                        protocol: https
                type: ExternalIP
