apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-gui
  namespace: proxmox-gui
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 16.8.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    portal:
      open:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: prox.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
          homepage:
            description: Proxmox admin panel
            enabled: true
            group: Utilities
            name: Proxmox
          nginx:
            enabled: true
            auth:
              type: "authentik"
              internalHost: "authentik-http.authentik.svc.cluster.local:10230"
              externalHost: "auth.${DOMAIN_0}"
              # Can be left default in most cases
              responseHeaders: []
    service:
      main:
        enabled: true
        externalIP: ${PROXMOX_IP}
        ports:
          main:
            enabled: true
            port: 8006
            protocol: https
        type: ExternalIP
