apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-exporter
  namespace: truenas-exporter
spec:
  interval: 15m
  chart:
    spec:
      chart: truenas-exporter
      version: 4.8.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Los_Angeles
    global:
      stopAll: false
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${TRUENAS_EXPORTER_IP}
        integrations:
          metallb:
            enabled: true
