apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: minio
    namespace: minio
spec:
    interval: 15m
    chart:
        spec:
            chart: minio
            version: 2.0.25
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: minio
    values:
        logPostgresImage:
            pullPolicy: IfNotPresent
            repository: postgres
            tag: "14.5"
        logSearchImage:
            pullPolicy: IfNotPresent
            repository: minio/operator
            tag: v4.5.4
        minioConfig:
            additionalEnvs:
                - name: MINIO_SSE_MASTER_KEY
                  value: 1n9lOX/teaVCtPvqDrU4il2cfWYBLD3ySXCeR3+TRXg=
                - name: MINIO_SSE_AUTO_ENCRYPTION
                  value: "on"
            domain: ""
            rootPassword: ${ADMIN_PASSWORD}
            rootUser: admin
        minioNetwork:
            apiPort: 9001
            certificateID: null
            consolePort: 9002
        minioStorage:
            distributedMode: false
            export:
                hostPathConfig:
                    aclEnable: false
                    hostPath: /mnt/Dendrochronology/minio
                mountPath: /export
                type: hostPath
            logSearchApi: false
            logSearchDiskCapacityGB: 5
            pgBackup:
                type: ixVolume
            pgData:
                type: ixVolume
        notes:
            custom: |
                {{ if .Values.minioStorage.logSearchApi }}
                ## Database
                You can connect to the database using the pgAdmin App from the catalog

                <details>
                  <summary>Database Details</summary>

                  - Database: `logsearchapi`
                  - Username: `logsearchapi`
                  - Password: `{{ .Values.minioDbPass }}`
                  - Host:     `{{ .Values.minioDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
                  - Port:     `5432`

                </details>
                {{ end }}
                {{- $_ := unset .Values "haDbPass" }}
                {{- $_ := unset .Values "haDbHost" }}
        podOptions: {}
        release_name: minio
        resources: {}
