apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kromgo
  namespace: kromgo
spec:
  interval: 15m
  chart:
    spec:
      chart: kromgo
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  install:
    timeout: 30m
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    portal:
      open:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: kromgo.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    kromgo:
      defaults:
        badge:
          font: dejavu-sans
          size: 12
          style: flat
      badges:
        - id: talos_version
          query: label_replace(node_os_info{name="Talos"}, "version_id", "$1", "version_id", "v(.+)")
          valueExpr: labels["version_id"]
          title: Talos

        - id: kubernetes_version
          query: label_replace(kubernetes_build_info{service="kubernetes"}, "git_version", "$1", "git_version", "v(.+)")
          valueExpr: labels["git_version"]
          title: Kubernetes

        - id: flux_version
          query: label_replace(gotk_resource_info{exported_namespace="flux-system",name="flux",customresource_kind="Kustomization"}, "revision", "$1", "revision", "v(.+)@sha256:.+")
          valueExpr: labels["revision"]
          title: Flux

        - id: truenas_version
          query: truenas_info
          valueExpr: labels["version"]
          title: Truenas

        - id: cluster_node_count
          query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
          valueExpr: humanizeFloat(result)
          colorExpr: '"green"'
          title: Nodes

        - id: cluster_pod_count
          query: sum(kube_pod_status_phase{phase="Running"})
          valueExpr: humanizeFloat(result)
          colorExpr: '"green"'
          title: Pods

        - id: cluster_cpu_usage
          query: round(avg(instance:node_cpu_utilisation:rate5m{pod!=""}) * 100, 0.1)
          valueExpr: humanizeFloat(result) + "%"
          colorExpr: 'result <= 35.0 ? "green" : result <= 75.0 ? "orange" : "red"'
          title: CPU

        - id: cluster_memory_usage
          query: round(sum(node_memory_MemTotal_bytes{pod!=""} - node_memory_MemAvailable_bytes{pod!=""}) / sum(node_memory_MemTotal_bytes{pod!=""}) * 100, 0.1)
          valueExpr: humanizeFloat(result) + "%"
          colorExpr: 'result <= 35.0 ? "green" : result <= 75.0 ? "orange" : "red"'
          title: Memory

        - id: cluster_power_usage
          query: round(upsHighPrecOutputLoad, 0.1)
          valueExpr: humanizeFloat(result) + "w"
          colorExpr: 'result <= 400.0 ? "green" : result <= 750.0 ? "orange" : "red"'
          title: Power

        - id: cluster_age_days
          query: round((time() - min(kube_node_created)) / 86400)
          valueExpr: humanizeFloat(result) + "d"
          colorExpr: 'result <= 180.0 ? "green" : result <= 360.0 ? "orange" : "red"'
          title: Age

        - id: cluster_uptime_days
          query: round(avg(node_time_seconds{pod!=""} - node_boot_time_seconds{pod!=""}) / 86400)
          valueExpr: humanizeFloat(result) + "d"
          colorExpr: 'result <= 180.0 ? "green" : result <= 360.0 ? "orange" : "red"'
          title: Uptime

        - id: cluster_alert_count
          query: alertmanager_alerts{state="active"} - 1 # Ignore Watchdog
          valueExpr: humanizeFloat(result)
          colorExpr: 'result <= 0.0 ? "green" : "red"'
          title: Alerts
