apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-broker-files
    namespace: mosquitto
type: Opaque
data:
    password_file: ENC[AES256_GCM,data:pQwKpVvI/dB4WFMrYPp2P+KSV1QzJY3LyVYKfwelOInSQ+XqukVNV2T91pO5OguTIAHMSAjZ8rhcvcAteiZevCLyzYJr13foUUAmzAfiY8OmNBWcF/20iXFVA/AJZMvH526hhwhd6r8pF28e8fge572Kfg/ZGwdmxuCTMzMjWvWVk6/FwCxh4O1fRGPwn5iYnuvMJWBocRZLb7Ie2QwQWJcOdLcdVd9cM7bNQ91k16QV0Vpx/abGLptYdsSjIoBXLH+b4O936VuQeDv+83BfNwShJJOi0NMwljb1sbgOb+I+3DZRdEYihQalWDBOGsbDM/mp/GmicIZ20wS+MIptcHEAI9eeLI1EZGqw8fFUouQQ9KIjhEMSEeiJ/snl9s36Y08kQBn2rYlELBUSXiWRe9EwixAVZFDOAcveXsg2CMRwbpjTwdUsLq5EZSJUowUi,iv:PgnEtgy0vKuAZfZU1Zw2INjt5TSbo+HGqtzfUgAEtKo=,tag:aXvxyVL06sHXZFjbpO/ugQ==,type:str]
    acl_file: ENC[AES256_GCM,data:rFFcRvwk0hmPSYbMRa2cXJWn+5e/7eJxBQ7awT/rHNP6hi6lidqL57yIf4IMhG/Z8iHOceUgezIkg4Xu8pVuI1sqTZiEXE4vin0NEt2VQTMEb3P0hyB5YOO+pqFjQfUWRaeppY1Ig/Of9G6o1OBTkWF9emfKs2sn3RxoTLqisPYu2rwTBPqG4ZgVYCc70YoLg3O8ZnS5EQkxtzNlnAK3c5eDHTpAdxF3Bghg6XngbFphuly2RF76qVrVEf5MHP9O6KhUgdCFIt8GcZOwrei5qVrEp3Xsm4Q2C4j7fcSExYM9CKguAtt3SjOqX763y6zyxl0dcnkUXyc2ekYW2wqSFLTzyA1jo+4NQt+oGRO/qgYFNXM3YoAL7T7vlTjn5WrNkrs4XbbRL6Yx46/aI6QGod22jympa/KuGVBn8KjmE1ArHdvVXIFR2HZMqvxf7C28hs2X7A==,iv:5pzJ3DELmZW9Ck1x3yiQaFaM2PPfqBOgbL4uXLBcYhw=,tag:NEkzOvtGBt01k+SEl5effQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcjlqMTZNQkNhK09iWVZx
            dzU5UkYvVHFKQ1dPa1llWjhINlVBc0xSdndVClliTzNoZks0MFNXc1Uxc01rSllk
            SlZCMThaWk0wZk5XVWkySjRqMHVTTTgKLS0tIGRINFVGMU9XaWpQa2pwSGJNMU5D
            VE5aT09TdStQQ2c5VUZvVU1uMWtxazgKU4z9ZJCvcCG1KtSuVn1TO07XKwIPPekM
            t9vIx+hTWrp3kZXjxFYjH71jIwyYexzS3KS3kVlp25IBxT/5S7Ik5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-24T20:03:07Z"
    mac: ENC[AES256_GCM,data:AvTZNraL+b2/fxHSC9z2GTuQtE5HACKZ+Bcl22nTj3kfQdtuMFF0jP+khB1DMi2FhZ+1qj7TyEug3SYfrME2qbvpVabLhTE5/Ou524z2xl/DDbgdfpuTzJfCKveoI0s5ll1sUPw/t6BSHSwnvKAJmBJ+vcKLpAZw0CMo5ILMRbs=,iv:QqORbsWFD6mXAkQLJ265OWbA/+mW5grLCdCRxH3yOYo=,tag:AJxcVzoyYxAe62Gn5egImw==,type:str]
    version: 3.13.2
