apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-client-credentials
    namespace: smarthome
type: Opaque
data:
    homeassistant-password: ENC[AES256_GCM,data:EvhsBX4liBBGvG3bYUsbXDzbHth6Isd6fhU+BbJ7rj1t53EE7PqnvFokeP5uhqKz+t/pmPQc3+cfBQI2,iv:xuenSyNjEK8S8PLkstvYc5TdtrV6UKZHj/LFCKo9mOk=,tag:+w6ox76QyEhOLR9zdi45qQ==,type:str]
    zigbee2mqtt-password: ENC[AES256_GCM,data:DyiV/TCwltnx1ucXTI9o+c0zes43Cp59bRPs7sraOezWTGL7z8bTMP28AiSiTc/OlTVUh9jOeK1Beeok,iv:Ohe3At15vhShaPAluvuHvUncD+Ipp99/73R27OPSH/o=,tag:y4wSTCoQ0PYPTMO74xT7jQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzN05KMFY4WWdOdnBFVVkz
            ait0UlR4MGpxSWRsMklpVXovcEVBTjFZQVEwCnNVRC9YZHlzN3RLNHhSdmxBeFRT
            NlFFSXNBL2M0VnpiU00yTTc5d0I1N2sKLS0tIDFsam5jSExySmQ1RjZSL2JqdlQw
            L0JrUDNwWmdvZXA5UmQzOElsMnBXNkUKInOVzCgUnG2TXGK/NPLpIPr+zqWIwJJb
            Z3CD4JiL3RmCMx0zGC8IP73JacB4qqy4In44C9qft9s5TyoPqCOtLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-24T20:54:38Z"
    mac: ENC[AES256_GCM,data:RqcNrALkt1yHPea3BACD4PGd4jrS/LV1qLY+Q8HF4iGBMyeNYLjaO2Ft3mR+YkUkxapZlq6jz9IDu7it2IspwVr0Jfd+/BDjbsTgY9P2pOY35PuX4ZkfVuGkmaSQPFmDdmuPxVtoWoPR5JyIBSh759V471axxg7+e2Ss3KpHQpY=,iv:0Mstt6VTG3x+WCllyKFXEmUN1CYwwNx+PlSAFGQBYL8=,tag:iv221QgHU4APOQ0l5epjsQ==,type:str]
    version: 3.13.2
