apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-client-credentials
    namespace: mosquitto
type: Opaque
data:
    homeassistant-password: ENC[AES256_GCM,data:EvhsBX4liBBGvG3bYUsbXDzbHth6Isd6fhU+BbJ7rj1t53EE7PqnvFokeP5uhqKz+t/pmPQc3+cfBQI2,iv:xuenSyNjEK8S8PLkstvYc5TdtrV6UKZHj/LFCKo9mOk=,tag:+w6ox76QyEhOLR9zdi45qQ==,type:str]
    zigbee2mqtt-password: ENC[AES256_GCM,data:DyiV/TCwltnx1ucXTI9o+c0zes43Cp59bRPs7sraOezWTGL7z8bTMP28AiSiTc/OlTVUh9jOeK1Beeok,iv:Ohe3At15vhShaPAluvuHvUncD+Ipp99/73R27OPSH/o=,tag:y4wSTCoQ0PYPTMO74xT7jQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzN05KMFY4WWdOdnBFVVkz
            ait0UlR4MGpxSWRsMklpVXovcEVBTjFZQVEwCnNVRC9YZHlzN3RLNHhSdmxBeFRT
            NlFFSXNBL2M0VnpiU00yTTc5d0I1N2sKLS0tIDFsam5jSExySmQ1RjZSL2JqdlQw
            L0JrUDNwWmdvZXA5UmQzOElsMnBXNkUKInOVzCgUnG2TXGK/NPLpIPr+zqWIwJJb
            Z3CD4JiL3RmCMx0zGC8IP73JacB4qqy4In44C9qft9s5TyoPqCOtLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-24T20:03:07Z"
    mac: ENC[AES256_GCM,data:scswYR/yF7zoXYe1YaCJtmoUjp69UgMgy85JtRzP3bnPClotrl/TibegFqUo/FjWkosTv9OfLcdtRQBbOhXKnupq5J+AySDn7iruaMzq4HnpIetSnXs9x8oTeVzUCi7vYJmhZGjVdQ/YVT6mYEKu89lmMgzUNi9GipIEtE9qsm0=,iv:hMizmssr7aO18P77bRd6TqvbfZl8hi10kKGtwR+HV2w=,tag:kSvJKmeL0rlDjOL5SSFO6w==,type:str]
    version: 3.13.2
