apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: mosquitto
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: home-assistant
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: zigbee2mqtt
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mosquitto
      ports:
        - protocol: TCP
          port: 1883
