apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 15m
    chart:
        spec:
            chart: authentik
            version: 27.9.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Los_Angeles
        authentik:
            credentials:
                email: ${ADMIN_EMAIL}
                password: ${ADMIN_PASSWORD}
            email:
                from: ${ADMIN_EMAIL}
                host: protonmail-bridge.protonmail-bridge.svc.cluster.local
                password: ${PROTONMAIL_PASSWORD}
                port: 25
                timeout: 10
                useSSL: false
                useTLS: false
                username: ${PROTONMAIL_EMAIL}
            general:
                allowUserChangeEmail: true
                allowUserChangeName: true
                allowUserChangeUsername: false
            outposts:
                ldap:
                    enabled: true
                    token: ${AUTHENTIK_LDAP_TOKEN}
        cnpg:
            main:
                backups:
                    credentials: b2
                    enabled: true
                    retentionPolicy: ""
                    revision: "3"
                mode: recovery
                password: ${CNPG_PASSWORD}
                pgVersion: 15
                recovery:
                    credentials: b2
                    enabled: true
                    revision: "2"
                    serverName: ""
                user: authentik
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: auth.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                    - host: '*.${DOMAIN_0}'
                      paths:
                        - path: /outpost.goauthentik.io
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        description: ""
                        enabled: true
                        group: Utilities
                        icon: ""
                        name: ""
                        widget:
                            custom:
                                key: ${HOMEPAGE_AUTHENTIK_KEY}
                            enabled: true
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            blueprints:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: blueprints
                      src:
                        enabled: true
                      type: restic
            certs:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: certs
                      src:
                        enabled: true
                      type: restic
            geoip:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: geo-ip
                      src:
                        enabled: true
                      type: restic
            media:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: media
                      src:
                        enabled: true
                      type: restic
            templates:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: templates
                      src:
                        enabled: true
                      type: restic

