apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 33.13.7
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: America/Los_Angeles
    authentik:
      credentials:
        email: ${ADMIN_EMAIL}
        password: ${ADMIN_PASSWORD}
      email:
        from: ${ADMIN_EMAIL}
        host: protonmail-bridge.protonmail-bridge.svc.cluster.local
        password: ${PROTONMAIL_PASSWORD}
        port: 25
        timeout: 10
        useSSL: false
        useTLS: false
        username: ${PROTONMAIL_EMAIL}
      general:
        allowUserChangeEmail: true
        allowUserChangeName: true
        allowUserChangeUsername: false
      outposts:
        ldap:
          enabled: true
          token: ${AUTHENTIK_LDAP_TOKEN}
    cnpg:
      main:
        backups:
          credentials: b2
          enabled: true
          revision: "8"
        mode: recovery
        password: ${CNPG_PASSWORD}
        pgVersion: 15
        recovery:
          credentials: b2
          enabled: true
          revision: "7"
        user: authentik
    credentials:
      b2:
        accessKey: ${S3_KEY_ID}
        bucket: ${S3_BUCKET}
        encrKey: ${S3_PASSWORD}
        name: b2
        path: ""
        secretKey: ${S3_SECRET_KEY}
        type: s3
        url: ${S3_ENDPOINT}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: auth.${DOMAIN_0}
          - host: "request.${DOMAIN_0}"
            paths:
              - path: /outpost.goauthentik.io
                pathType: ImplementationSpecific
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
          homepage:
            enabled: true
            group: Utilities
            widget:
              custom:
                key: ${HOMEPAGE_AUTHENTIK_KEY}
              enabled: true
          nginx:
            enabled: true
    persistence:
      blueprints:
        volsync:
          - credentials: b2
            dest:
              enabled: true
            name: blueprints
            src:
              enabled: true
              trigger:
                schedule: 0 8 * * *
            type: restic
      certs:
        volsync:
          - credentials: b2
            dest:
              enabled: true
            name: certs
            src:
              enabled: true
              trigger:
                schedule: 5 8 * * *
            type: restic
      geoip:
        volsync:
          - credentials: b2
            dest:
              enabled: true
            name: geo-ip
            src:
              enabled: true
              trigger:
                schedule: 10 8 * * *
            type: restic
      media:
        volsync:
          - credentials: b2
            dest:
              enabled: true
            name: media
            src:
              enabled: true
              trigger:
                schedule: 15 8 * * *
            type: restic
      templates:
        volsync:
          - credentials: b2
            dest:
              enabled: true
            name: templates
            src:
              enabled: true
              trigger:
                schedule: 3 8 * * *
            type: restic
