apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: radarr
spec:
  interval: 15m
  chart:
    spec:
      chart: radarr
      version: 24.1.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Los_Angeles
    credentials:
      b2:
        accessKey: ${S3_KEY_ID}
        bucket: ${S3_BUCKET}
        encrKey: ${S3_PASSWORD}
        name: b2
        secretKey: ${S3_SECRET_KEY}
        type: s3
        url: ${S3_ENDPOINT}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
            nginx.ingress.kubernetes.io/auth-method: 'GET'
            nginx.ingress.kubernetes.io/auth-url: http://authentik-http.authentik.svc.cluster.local:10230/outpost.goauthentik.io/auth/nginx
            nginx.ingress.kubernetes.io/auth-signin: 'https://auth.${DOMAIN_0}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri'
            nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
            nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: rad.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
          homepage:
            enabled: true
            group: Arr
            widget:
              custom:
                key: ${HOMEPAE_RADARR_KEY}
              enabled: true
          traefik:
            enabled: false
    persistence:
      config:
        volsync:
          - credentials: b2
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 45 9 * * *
            type: restic
            name: config
      movies:
        enabled: true
        type: nfs
        path: ${MOVIES_PATH}
        server: ${TRUENAS_IP}
        mountPath: ${MOVIES_MOUNT_PATH}
      downloads:
        enabled: true
        type: nfs
        path: ${DOWNLOADS_PATH}
        server: ${TRUENAS_IP}
        mountPath: ${DOWNLOADS_MOUNT_PATH}
