apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: ollama
    namespace: ollama
spec:
    interval: 15m
    chart:
        spec:
            chart: ollama
            version: 7.11.14
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        global:
            stopAll: false
        ollama:
            registration:
                    enabled: false
        TZ: America/Los_Angeles
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: chat.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: true
                        group: Apps
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            config:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
        resources:
            limits:
                nvidia.com/gpu: 1
        workload:
            main:
                podSpec:
                    runtimeClassName: "nvidia"
            ui:
                podSpec:
                    containers:
                        ui:
                            env:
                                ENABLE_OAUTH_SIGNUP: true
                                OAUTH_CLIENT_ID: ${OLLAMA_CLIENT_ID}
                                OAUTH_CLIENT_SECRET: ${OLLAMA_CLIENT_SECRET}
                                OPENID_PROVIDER_URL: ${OLLAMA_PROVIDER_URL}
                                OAUTH_PROVIDER_NAME: Authentik
                                OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
                                OAUTH_SCOPES: openid email username
