apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:fsTcZujPJJAeH2ZfvUclZipUOG18YRf5a53JPbeWkK4PPu1FDS5o91Zu9Mq1t86Khu7sEJjN+MdoaCKuyi0UwF655cdTz9+O0uB5nGERKkwzRGnMuk4qiTtoDj0Q,iv:qmvVqC0P7dQ109fnvZUPvIG7OfolfPqJqSN/P5MMZCs=,tag:1vLZo6BG5VjnxTBGDWkOnQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TS9SVW43VUl6Wm8xd0JQ
            aW9ZS2JlQm96LzNMdlkzTDhCU0c0cHpxbGhBCnFaaklETU9hSzNUaDhkdDErUWZN
            Rm1wcDFYTGw1NVhtL2Q5aDZ3UUNKaTQKLS0tIExRT2VFOUJwc2o1bkRPck5XMnFN
            aUwzYmx2WnU1cWxuUU1QTUxReUdsVU0KA4PwIEuEuOIQOwLvLR7tg2oJ/ajLRG4f
            +IQUCpzIedMCWuYWl5ChDz5NaNNpY0Y9IzRI6tTE8KemFgRlqtuw9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T06:46:40Z"
    mac: ENC[AES256_GCM,data:PafUF5tCeVGZABFtus/EVaqIoEIZ6qkyWiLydu/tGNmOSJFLvZjrnnNc5t5EKdheF6/hdAyypC4hmmDcfnNXBBpZkonSf3oHdWAtHPcBlEDKgiEj+XY8qMF+i3dojBp0ZqFKQnmcWL4mPWbVLv1cQgRcUcoEFu/9+HuuDs2O5tc=,iv:5zNr4oiOva/EZQkRtOvXUNHgGNbWNPYQ8xEjGl0bP0k=,tag:yC6jCIyh0KxL+P1hbpemMA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
