apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ROmqU/bSceufcMqOci6rKzfsTgSw56X+W5mdximgFNCnkedcjgOneiL3sRR+7bA7laocxWWpwKgqKCHoqrO6HoMXTdztH9AdYdxG+6JNb5w4noY/H0LA25cpQcFL,iv:szQsyy1xgiwuJ0xXB0nq3AD3zD0QUzzJGax02PX6XoE=,tag:urK9YOKrRWG3HJFiL5SKmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUC9acjFtUSsySVpNb1VV
            MkdDK2tJZGVNcE5YbVNZb1FUWEZqQWR6Q0YwCjVEZzc0UHgwSm9QYnpqc3paY05p
            MHc1ZG10MHhLUlZWbEhHMk1BdHFHblEKLS0tIEF6Z3JoNTN2cFovTk9LSzJEOXZk
            ckl2NFFDeFNnUFl0WHVnbjhldlc3bHcKlE+3JReSz214Y2GELBHE81xr8TMUhOkv
            ofZt3/gnM9hKjQOxadS3B/4XRGKuueH8X9CqauHql3/dRpbFxD3SmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-08T17:12:40Z"
    mac: ENC[AES256_GCM,data:EKkVwt8NZQoiPpOsO+NqE5T54eaLpi65KqxPwzmkxPj+ttu4n2Z6kPyljmFywRr9cjOGcBwflqsnfxO2bY4f866aD1xsRVMqrVYbVWLm97Cwlg5F65m0Pt4uq1KZ5mAl5maq1helnn33gPmAv+17slBgyjoEoDUGJKhgShwDOuA=,iv:5Fvg4bQkxiLY1rJqSGJltrrt8j589Bx0g83ISTjfA04=,tag:Nvtwrd1GLf2dwJAHVlhCtQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
