apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Tndz7fzZDGCSFuUJYbbsUOzJNYgIUsaA1VZur42XGzLbbOekW/e+9S0vcozHEa5BqSByJ7/scDdqq7YCqRvA0GHw3JwqhLvoGrQmtG4buKwOLcLkcapqfr/ee41k,iv:InXt/6SODb20K7jQ+zOMKYBw6f33BnAKg7SpjRHTzLU=,tag:jcVNlB79wa1lwxtsKwdj7A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1S2FMSWpRRnF2cy9QVXZz
            c0tTTm1qOWx0Njd4ZGYvKzVWNVB5cHl0MTNBCmhXc2RST0l0WGNRSXl0QWExR3Bs
            ZlVBeG42U1BrQ08yK1A1Vzh6Q2w2WUEKLS0tIG9Sb2k3QjBHTHl3RzdzU3ZEYnFX
            SUh6K1lETDR2T0wvbmp2WWwyZ0F6VDgKnGZutmlCpOd0XRCT3epo3DOpxxIuQXl1
            g4LM255CG4nWtWiGjshaAKoGpsDOOuBMa8O8Y+4SZaZbChqDU1LJCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T16:15:50Z"
    mac: ENC[AES256_GCM,data:IcnVC0yQL5QEiaf3mMaqzLlB2XjjzhxjQ31JLwit1xM1Q93Tz1i7bc/3yCGfbO/acoNJBEV1kcw3vqTjvtTkF8lWjI7byuw+rjqEjUVjkGrAotyOGkhk+vl3KSZL+K3qIMf1WmDxNFzZNjTMf+jezsM/uTojEYWCdwVgeRv+6eU=,iv:jQAzAzhgtH0kX/S2aai9d1u2csVlhcn2FYrXpAfugKw=,tag:3Rv6DQdl+iZaY1DXg5/84Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
