apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: emby
    namespace: emby
spec:
    interval: 15m
    chart:
        spec:
            chart: emby
            version: 22.0.5
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        TZ: America/Los_Angeles
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: media.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                    - host: emby.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: true
                        group: Apps
                        widget:
                            custom:
                                key: ${HOMEPAGE_EMBY_KEY}
                            enabled: true
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            config:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
            movies:
                enabled: true
                type: nfs
                path: /mnt/Redwood/media/movies
                server: ${TRUENAS_IP}
                readOnly: false
                mountPath: /mnt/media/movies
            series:
                enabled: true
                type: nfs
                path: /mnt/Redwood/media/series
                server: ${TRUENAS_IP}
                readOnly: false
                mountPath: /mnt/media/series
            music:
                enabled: true
                type: nfs
                path: /mnt/Redwood/media/music
                server: ${TRUENAS_IP}
                readOnly: false
                mountPath: /mnt/media/music
        service:
            main:
                enabled: true
                loadBalancerIP: ""
                ports:
                    main:
                        port: 8096
                        targetPort: 8096
                type: LoadBalancer
