apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: emby
    namespace: emby
spec:
    interval: 15m
    chart:
        spec:
            chart: emby
            version: 22.2.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        global:
            stopAll: false
        broadcastProxyImage:
            repository: docker.io/alpine/socat
            pullPolicy: IfNotPresent
            tag: 1.8.0.1@sha256:d6450f96ed8b389f53929dc8ba0a4c42bc1db66d613efe923173a181f1256ca8
        TZ: America/Los_Angeles
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: media.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                    - host: emby.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: true
                        group: Apps
                        widget:
                            custom:
                                key: ${HOMEPAGE_EMBY_KEY}
                            enabled: true
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            config:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
            movies:
                enabled: true
                type: nfs
                path: ${MOVIES_PATH}
                server: ${TRUENAS_IP}
                readOnly: false
                mountPath: ${MOVIES_MOUNT_PATH}
            series:
                enabled: true
                type: nfs
                path: ${SERIES_PATH}
                server: ${TRUENAS_IP}
                readOnly: false
                mountPath: ${SERIES_MOUNT_PATH}
            music:
                enabled: true
                type: nfs
                path: ${MUSIC_PATH}
                server: ${TRUENAS_IP}
                readOnly: false
                mountPath: ${MUSIC_MOUNT_PATH}
        service:
            main:
                enabled: true
                loadBalancerIP: ${EMBY_IP}
                ports:
                    main:
                        port: 8096
                        targetPort: 8096
                type: LoadBalancer
            autodiscovery:
                enabled: true
                ports:
                    autodiscovery:
                        enabled: true
                        protocol: udp
                        port: 7359
                        targetPort: 7359
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            resources:
                                limits:
                                    nvidia.com/gpu: 1
                    runtimeClassName: "nvidia"
            broadcastproxy:
                enabled: true
                type: Deployment
                podSpec:
                    hostNetwork: true
                    terminationGracePeriodSeconds: 3
                    containers:
                        broadcastproxy:
                            enabled: true
                            primary: true
                            imageSelector: broadcastProxyImage
                            securityContext:
                                readOnlyRootFilesystem: true
                            command: ["/bin/sh"]
                            args:
                                - "-c"
                                - 'export TARGET_IP=$(getent hosts ''{{ printf "%v-autodiscovery" (include "tc.v1.common.lib.chart.names.fullname" $) }}'' | awk ''{ print $1 }'') && [[ ! -z $TARGET_IP ]] && touch /tmp/healthy && socat -T 1 UDP4-LISTEN:7359,fork,reuseaddr,rcvbuf=8096 UDP4-SENDTO:$TARGET_IP:7359,rcvbuf=8096 ; rm -rf /tmp/healthy'
                            probes:
                                readiness:
                                    enabled: true
                                    type: exec
                                    command:
                                        - cat
                                        - /tmp/healthy
                                liveness:
                                    enabled: true
                                    type: exec
                                    command:
                                        - cat
                                        - /tmp/healthy
                                startup:
                                    enabled: true
                                    type: exec
                                    command:
                                        - cat
                                        - /tmp/healthy
        autodiscovery:
            enabled: true
