apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qMOr8deV56jEAlL3Mh359jvP2Xi+w7QLKDjSd0QqJQvVadvo8iOBm7qlpSVLiHfaCU8DxWPLwrG5DTdgzucUSDRRa876sNAAGha6ewWrXsoHZNZI504xdIgVrSmOfhipQYkEZ/rSocigDCK2sMwCuwwHNCshR9zkJ19e1xvpnWeGkq2CfJNDaPAuGsePWmo9FKQFFq3/nhwat5vAnXg6yP1tBzpvjViXsQmgGVSAxCW9ICILEBkBFZ40Cd4rw6P93B3/gDQhZl1zUHg1vsTKSkH0TGOAhbEApAo8FBdjPMKPwpntzX9O/ZSrDeHgFJGG8wfztwXLrGJ5lDagYCUmtSf/KVUrzwTCfMY6tetg4qnkoeRToNsZgPx65QFcqCTj,iv:H6+9c/1YsP0loSWhWeuGBQ1b4lSdc0zGnaMuvZCK2es=,tag:10+tMpF9/4y11Yi4Fs68vQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:3rrjVRJoBnOEau+215NXUvzt3puLkmFuNuXgvgEsHm4JigN3x8xcFrP5zWHx28qm9a8K09B9RNhsGBEclUl0qvgXc5nu2teszOOVVuCxj8cf9rzEuuimcolBa3gsyU+F5xHzXRIH4PPiC1hu5bnKyZM5Eq3jdVI2BhKSf9BziSUXr0qjGV27aG+MgD1EcRJALOFD6SlJw7hKRdH3IjsaJ4VbmLcCzCr2SVIirFbGfVslm59k+pDlChthK8Q4PXctTpi59/eLarV9nALeUg==,iv:2X+naes7XbT8qbf7TAm/gNjPrXZTe08ivhWscE0iO7E=,tag:3KZjfQFpMlRJHWxaIzKGrQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:IVM645f/NVMzH3KEND/YW3NeaADkpxVXGHoYQMbBm+M15M0ZdJXq7ImySuTArtjGkTV0Ke/PyXLT9XF+ZgbiDqSbfF732GCTMcmWgqq6XSReLBrOucqW1D91mv7NXlV8nIdBE89x3ORRkSJYJgpIcUrK/OCDQOsqMANzIVvA242KCSsepg9Tzy3g6SOiJX6jZ0/ewUxj64vu3HFLgw641AFz6qEtWd/ZNDCb,iv:hMrTuHrdoibdlI4If+WwLf68NnF9qtIzFE3YTHqRdog=,tag:ExzP3vFrzLYYUhEYezgTbg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dHhYaW9VTXh5ODB4M3VP
            b3l5U1hJbTdKTXJmcTAxZ2dXMmVDUmo4MjNZClFsTzVYa1BMSjNKYU8vVXg4akF2
            dnQ4QzcwYXA2dVBrRHVJcE5PbThEZ2MKLS0tIGowbkxMd1NwTE9ZQ1ptb3FKeGxv
            OWRPYUpsYnlNRTFTSGx2bWtwVE1yOXcKsLR9vUPKJKNFWlbqK1PbAm7ABXsEKZ1F
            An//jSLUItp8RzJcbPswu/sZ1dLXzBlGRRRcP1Edb1v9C6opI0qqeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T19:01:14Z"
    mac: ENC[AES256_GCM,data:F58tTNZrObUYeYYjkQryemVoOfOYuPr0h6l+swKnFNDmaNS9RtlfCDhOYq1RZYc2CxhRdDGdTLwufkxvVQW2vd+KK5mCe9vaA04X2OSrS+YayFNgpz8awNhabpxl9yemM9b+vKB9P1fWm+K1NsIj/egRR1ZHGfIzxo8plgDpxMY=,iv:+fHwm6z+mQirzyse7wr6yr7m8HWnidZ337GXj9AAmU0=,tag:cUQHiTW7TlulhSYgSsxZUw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
