apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SWFm3wubOVXs0+JYPXXe7exdgjeAFRIy4/XGrHcY4vjiooAcxujVi8D//ryQMYTVuOWrfiVbZXnsQL1mq4U4NpBP768q5zS7WfAss3YDhhZldVIemMyfyV2Qjp0GZIBN3T6PHX/gUZKUQXjkz8VUBPzaoyJrtT01LJ9PGyjREqcthVzTQz4szRPEQbbFllxmP7EHpHT+N3LabOXVwcHSiN1lkikEyY2vrVeHj1oJGWrIvcdnr4rh6P2tqueeUYqVNp3HHOO0NgZbzjvALLO3DgfpWTtJucr6TWDJqSA4zyadeIIS0kphhgrG/0eU7UTP+HiWvTzT4I108Q9AQdYIsQgSi6GXxhxXZky/WXkBOWJNOjBX9CaoJRgf7yCUkWFC,iv:kaRubmsVYGIhLlxZ7ju3lHTv8NqxlADj13b9WPMlvNQ=,tag:hbt7z6MwyKRKKYDQXyoV+w==,type:str]
    identity.pub: ENC[AES256_GCM,data:RaHuEhIpyi6KkGxXsjOsR0Rike/1770fiydsaukAgPgPpKIBmCBaSxPULJ4wTBP0y/dh/XTF29rSnOZHPk+BaMkhSB4wsleXtkgylLJOHU6TpZMvpcqQfQ+yKadfnLQpEsQ08TqKkmzFkxZlpTmYt1ZS2RADs+F1Co9SSBtrUuaxhSrAZZQXCWw1MytoWHgtgkJh2vWATOpujWW4/vMasp5qVia2a7yuHbGf1fYX0yOWtg/bIYfxK4/Rt1DuYaxHL8uFrBjFVAbaSBZBrA==,iv:4rvJMyh1GM4OQk2+T9bW7XP51oooOlizF05rTkojqTA=,tag:AqJWN8Icz1WzZtbZG2Z/tA==,type:str]
    known_hosts: ENC[AES256_GCM,data:t9KT2WSGO9BjzUVlsxTWLL0zka1sRVVzAk1qsBlN8qxQ5NY05Ai8ao5T6TUXaLpTd4RFs0v4RcLNASmspCyt+33ZslI2eg8Oa3zGhEvJVqW8pzOPJ4yl02bNXnehp1n7aXzm0EnPLXjjZdJvsfbR1zS2wqXSEgEcXSMTm4jYAkHgq98u/2UPaP4PDYpb4YWuH8u5pDQWi8BKfH5lJTG8DbQsy+Hc2uFx/1af,iv:qB7osysgGcOs1TB/hOT04fCAZXg4n3hPL17lsqJTxO8=,tag:K9YzbmqQSqqxWhKmkaPZVA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNWhuN0FQdTJxcXRkUmIx
            cnAzZzVVRHkwRUJ2dVcwZ2VZZmZaS0pmdnhNCkN0NWQza1daMW9wSWtUUnRNNDBt
            ZFFnbGlwMk9EZ3VyckZsZFExaFE1aXMKLS0tIDd1MGI3Q0lmbmtieWkyL3Jicm40
            cGZQVHpFanFkWDJ1UDEwcTBnYld1SEkKY9351Bj0NpCM3/w+fZtr027NFhuB1pme
            Re/6zWhsWADtZffMPYCCox2C58+Gsk1lrI1LsJFLYt6M+cj3s6nVrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T06:46:40Z"
    mac: ENC[AES256_GCM,data:HHXzVxWHggwDX/3rPpCuuoHy3rUak95NZs/ev84GdwN+lV79jbb0+82jplTCC9wGf2yGKkiJ4w+siFjkeuO0LwYUVCOb1uBwHHmiuu+h3Lgw7sMYaGafEMrO+zTOHonCIRxFMhktiRQzjp75XNUodPCAvb09mH5tPv/G9t5kH/4=,iv:BdDwZhHr4bj127bI+nsIk247DHkl5OsiotzhNOqjO3g=,tag:QVi7yjlfe4HN73Ngjk2pGQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
