apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:W3eO4xnQLCG8t4VV2pgO4xq5HRmxunuOLzirKAbK4aXUSrWw/ArrtndCZHxQBwAT4iPoECec8VQyvQjMCcryWWGCo8vxYEYvJwc8ibZUI1KqkfBNE8QW4V8B86BE9QYcKgIr0Wwo9ClsEmHExoQ68vKyLO0bewsm7ZFWV8iArY7IL+sTho4sWGk6tQKBqePoJGRKSc9ZdBtc3knsfHBDyPQJclnOnXq/jjs+spANFX4wUIR+j2IdxsyRd/Aadk3KtvUe4CNLqS4BL1lf89l6k8sDcT/cFwLwvNRwg7bBkufex0a7hJZllLDBKca77sqzoH+TmfNG15R9GHRXguf+rcfWmbh1Con15kX+WR2php6ckbExDVMqjhjA2YoDIKjt,iv:JBqXbqiXxfRbwc2SFr7YfJyEDAmI27ek2Lg44pxBTRA=,tag:pmc1L5ZSfz6/HrxMwgIoyw==,type:str]
    identity.pub: ENC[AES256_GCM,data:zEiK6KLDHLVuqpqNn0T2mAw+bNIM83jRZ+TsQa3yy5EUyHxgwt/GqbQQocDK9AkbN4bxPAx6SdBMZ5F0++DS/niJrJF3LLSFV0sFHlbckmlo/1I0b0PjMxmz/uUiBavvuGdzPff9tP2i+Xj4Th8vhGDljkwjx+OeLk5NC8wPLRz1FzqqBUUGqyDLW4VGAXHJO4zJhPKjT8eoGxwJr6KWCOSkOnEgLqBf+ttcnMFS7W60/0fQGig2D5AdPaDUslk6LfYvlAbqj0RNLmcF5A==,iv:qrmlk0onJAz4VorwvaHsE4bMvK+n+SRM4FwXMx8AJ6A=,tag:8wQ06RK0W/PNzkQFnxBH/A==,type:str]
    known_hosts: ENC[AES256_GCM,data:OkSvWq4Nl++PCkyy1y8kBUMuDcmPvBAOkTfeRqX5D77bMY+0Lf4el6XQ4mL8G0Srki4mMqINIG9NB011aFLmetuMQL72KhZQ1EWaunOul/Blggo63VzZesPRrMoipyk4ZDjaREUXzwOkKqCpZCbE0h8cmMB//27RK3HciZQwoiw7iPfoQeBhS1R7vqNvBtj6qyk/uPS6mH00JkQhQEluy5MGHD/lEo1EG5e0,iv:HJrNxm16hSS/l3IJlsTdoZP0t9cN87u7k4MQsMRhjvk=,tag:MqpVhhKF/YhXl2cEyjGITA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QllTcVNLRTRtSlZZUi9I
            b3NqUjF0QTBTRXVtb2R2NGNOc1dTdloxRmtRCjVYQk1lQmhMYXQwU0dnNndHd3I5
            QWp5YXZpaEV2WlhldzZ6dzdnOVRTR1EKLS0tIEs5Y2lqVmNlcm1XYjRwNXVHblA5
            d2Q1ek9iYmZjd0NFZFcrNGdlZHE1L1kKKH87qRgKNBG/OTo0tCOxaBYqQVQIRL95
            NwXrno8W/UpHr+MFl69qlsHp3urRPE/aeiacpVmSG90xUrTvPO7fMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-08T17:12:40Z"
    mac: ENC[AES256_GCM,data:SNVMUpFLpUXhd778xFSM10cjZNw5Oy6UDNOvE4evy87bj5Oc1SrPUUQI2KrLhOc22iXMNw9GQfxvKrcdmIMq9OPrbJ7T07oM8LYoZtKoS7PNaR+L10IoOSXnyeXrfwTSrPS8VbF/lwgF4cEMw7JA85KJJgLGOn4AKWMUTcqqoEw=,iv:XAsBn8ycNRy36Osd+4dlB/OwOusLQ/9AbOdEoO6laVA=,tag:orTcpcYmIr+F1O23HiPHXQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
