apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:FVTvaQYphLPaJg4Q5yAnhvA6zrrc9+pH9w/TlvD+WC9P83YbsbqEqYMNY60N4JouTPmVcliKhz16pxlW/87nmJ4YGm4ps/DdglgX+LGnF1OHvYU5LwAixYC8/G+9WFIyQX2x9O4uiAZQCnJbMBBcq+Kv9FZwkvRsHg==,iv:QQI85yBPBsmIiwXUpT4ysjLA7iSsCWd6WY06WlE2msg=,tag:6ftv9DyWQoNRo72xhETk9Q==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:/EZCE9EZlJMB1QrCkl/uhSAK97frXa4wDFZSBVBriMVxD1F/ElGpYiH1O9sCROdG5YHko4qtqTHGXAy8NHuoCQ==,iv:MFY6btKC1ViXeNfe2IlcWESgc3qWGb7Zrc88VrMpdnU=,tag:eB8V/QWcfcTPfqwS0dGiFA==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:FuYBAjUx24O5p7VLpy8J6hZL+WrYhf6Yv6Py2vZF+znQFAB/7Rs502Xy23Kzp0DCiv2CTv/UxGGlC9uRecR+3KE8r0OYlCFZVCK10Qbn8m7Ckr+H9Bc82jHadzDr,iv:RubbCpzYi5UWm1quP3SUfnpFPgrqpxUEhGU6Et7CRBU=,tag:eh7HcYSsnQkCTybhXeUdzA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSEpFbzVPeGVhMVdRV21R
            QXB3dTh6OXBFUXNlL0dxdGJPTnI0RzhIMW1RCjNxdldvMzhzYlVPQ0xuMnR2Zm8x
            MW5yZjJVbzFoa1V1eXZsTzNOcmpISHcKLS0tIDNSTVFrUThQMGJNeEdnUmtySUJ2
            RThoQURBdWVkcG9yTFgzTUszL1Ewd2MKVjGfsQdAtotxODzgAWJk8UyBbAvQD/OD
            s0ainkId6cKRVW5g8c9cwqjVI3ss376A1B72sy8RCmiVvFBMhRrhjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T19:01:14Z"
    mac: ENC[AES256_GCM,data:W5ZeK2je+w+V4YMkqALcg1U7eLq49L/ZeY+fo04zLLTkpLI8g16aNlT5Ke76aXZFhMi6kjRihw1wr3QQuNhhh16EXaFyMOa83YMgdLW21T8Qv4D28EQjCnKajk6TetWAE7CZy3h9R1IUBou0+1oCA1YhLD0O3YhvLO2l1AvM1Z4=,iv:EGtVCNfr6oOtdsdy7nf06Oxztf83U3pqETf7G6cd5s8=,tag:JB1H0pZeUXXjv5+iwq0Oaw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
