apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:3RtWc4lfKP+gL5TpTCWtH/TdawlD483CSCC+vD+FqUh76ccEfa96zoQGqENewsLx3tCt+Q97IKXe/w7+K6lVD8JEyd1s7YFiD6ywO4fwnART+hKGwsl1jPVVepJTiwYborVVJ1jQSywj9Ai0Q8ve7+S0BYH3sai49Q==,iv:1hbEYBlsC0a/6lH3h1ajWhzERVxCdxEXkX3ZDAtSXqE=,tag:MZRV+yHLFfVKIijetvTv4Q==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:dXGGc+Jv0lUTE/0G/VCoEd7FBobOLUjz/AA9IFEunivbUbpGffudD7Cp7QPpAxaXAg0woNVDBBLCuYKXXgLXxQ==,iv:C6NY0xZMdRDgrNIgK8evowedBZO8H9n0PuCR9xKyyOY=,tag:VQK+hDeMwpRXqPdsbmiKWg==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:ebWeLl+9WTUvI0sS73cILLnbq0YsSvk+BXt3BmiemrNzeQI5ZrgNyqWinCzJsWtBjogzSjgqadzX0kfS/K+1BnNPdCb9Z4VBhXhRXC0qdzsx1qBExWmJt40CJoFw,iv:W7JMj5UoUUoHhhYDoSq951gXjYB1/lZivIqfaGtA9DI=,tag:qHtEMnHuBDuoRL2VDPil/Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaDhVNlhlNS9kQzdCTEJx
            RXpTOHpDWkhGY0Fnd0U1azJTRmhETkFkb25BCjBNYnFtQ0Q5RTdvMk9LaklsVU51
            R0thcU1ndCsxZjlOV1ZBWmE5R2MwMW8KLS0tIHY2Z1Y2QjlXdHpwRk13eitHWWph
            d05tZml4ZWVBUkdoNlF1SENVUThxV3MKo6FXmhCVhvAk4qmiV9x0Tjwm9dRKVBV/
            k9X1hpOKCqP3fZ1CxtCmWUHlD5FjroHtvHEcDkhQTQIGjaPBWxDQxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:37:13Z"
    mac: ENC[AES256_GCM,data:XJ+untTbvMcDKp7jk2addL6M8Hv4yG2e2c6hcA46I+QwFFNAyL7PlIUXFDeO58dMREGVeDfQAIkDrIRB/Nl2fVKi71n4pr7zUPA5iKpukzfRie/w76GxnztHxqsJTpz6iVrQ9sZhjXYs/NEEf6T5klOQg0lhLef2gL4MM8azvx4=,iv:SLytEavAfwlPKA5wSwKcWIeFb6QltUOlbOMJKZplIsI=,tag:elR4dfIj7u3UI8KuH4dtnQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
