apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:p9DtchwaXVKhDd7XRcZhmkxr2CREHUhcJoaA4NlLEfCZ55ayEvQwK3rksL6KY5bjT4ylB6PEmFUWYDztFKZjr/8Dusnb8UiyhZ7L9nRzCtpBMOvyC1GRwEAYKNAPUmfXRN4wIFNErklnOYYEA1azYOhhgOILxNeo9Q==,iv:tapk1/qiVi0KXLUWXCoZCrrzntu/Ehyv7Ip9mXyf1gs=,tag:W1RGhxh1i8J3Hj5/TzaI6A==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:yNdfcExJ7Q3z79xSWTbP9qKc5vjFXJ/tlnykVzcXzZW1PYN1AnlC8241CBur03ajvywuftjhZc+A1L8922qmAQ==,iv:oXM2E6AiZRZb1AVGarWszdamjU2vR2ttnEkQGhcobEY=,tag:gBi+JRsCROgcGBJofxs9Bg==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:WF327dDeG6jzQFRm/d0CmzijrX2JwLCFjdyVTuGIiP2PvG3ks0FaJONHUXQCgYQyXVdV6Q5nehQ0dXYrVRh2EseOFp/VHuZBkjqMtxu52U/ADMCMCge9r8OhP/Uu,iv:BFGawDv1TQC5MthCRDY31TRW8LJOHXLBnSN0odrUaBQ=,tag:NA4VUNmBP3sz2LutpeQcaw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYUR0bTVHV1NyR2Q0dXZV
            VS81VzNoNER2SlMzektpUlJpV01oSERXTTBBCnJOZE8xclNpRHFDNnZ2UmhCUkRX
            djVoaDBMd2s5bFdCb1V1a0pLWFJLTzAKLS0tIEEzem1WWStXNFlqR0FFbkZseDFB
            OWI5d0VaaDIwRE5ra2JiZDUyek9rSUEK8pLuIu+rLzURVXRYphhBqZPTwsdQx0Em
            UFkstuyVfiltCLyihbx0GqZGfA7BcqcLvPwf5G2oLm/YG8ns/VKZCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T06:46:40Z"
    mac: ENC[AES256_GCM,data:7bF3NeHmGYQVqjZ52RxOO+UwrX3z+5rZWgHc1Rz98bDw8dytyg4MPYR7/Y11SpY7uZTqGcE6EY46oz7kYZ4ftUowd4dsfmsz3EnUFEb6ZM/U4ps4ZAPnyXOLW6XzrVCM4zNhu6cyy14kM00cBi6bhmIZ96dDm3dcbCLFgXxexwc=,iv:BhB71C6I5qLPnTRL8Yla0JnrMFbVX977m2B80seIvhc=,tag:XHtGtkJjVwmMYo+nA5e0wA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
