apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: recyclarr
    namespace: recyclarr
spec:
    interval: 15m
    chart:
        spec:
            chart: recyclarr
            version: 12.7.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Los_Angeles
        # addons:
        #     codeserver:
        #         enabled: true
        #         service:
        #             type: LoadBalancer
        #             loadBalancerIP: 192.168.1.219
        #             ports:
        #                 codeserver:
        #                     port: 12321

        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        persistence:
            config:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
