apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: lidarr
    namespace: lidarr
spec:
    interval: 15m
    chart:
        spec:
            chart: lidarr
            version: 24.6.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Los_Angeles
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: lid.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: true
                        group: Arr
                        widget:
                            custom:
                                key: ${HOMEPAGE_LIDARR_KEY}
                            enabled: true
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: auth
                              namespace: "traefik"
        persistence:
            config:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
            music:
                enabled: true
                type: nfs
                path: ${MUSIC_PATH}
                server: ${TRUENAS_IP}
                readOnly: false
                mountPath: ${MUSIC_MOUNT_PATH}
            downloads:
                enabled: true
                type: nfs
                path: ${DOWNLOADS_PATH}
                server: ${TRUENAS_IP}
                readOnly: false
                mountPath: ${DOWNLOADS_MOUNT_PATH}
