apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cloudflareddns
    namespace: cloudflareddns
spec:
    interval: 15m
    chart:
        spec:
            chart: cloudflareddns
            version: 11.2.3
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: cloudflareddns
    values:
        TZ: America/Los_Angeles
        cloudflareddns:
            api_token: ${DOMAIN_0_CLOUDFLARE_TOKEN}
            detect_mode: dig-whoami.cloudflare
            host_zone_record:
                - domain: ${DOMAIN_0}
                  record: A
                  zone: ${CLOUDFLARE_ZONE}
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        persistence:
            config:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: false
                      name: config
                      src:
                        enabled: true
                      type: restic
