apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:3oqNmaSDp/ZKB/NTbAPh0BoTXAIZpnP4VasQ4WRWfeV/rZX4S4fYqpz8StGPNBdXfb0AhHxehZvsw0mk9KZ7ITl3o8ih6MQ/le1BcJ+jmGOSIdqhkV483a64XUo4k6LypzRmnSveLgzOAt/MxKIRibd+Tcu6yJ5IHQ==,iv:RXOcVKq4aIyjD4dAiTELO+3hBN+IWhsLMIH4CDooCfc=,tag:kKnP9BciKHEQ++9CNn4Mcw==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:3pCZ5HekMVL3yN8pwAYcWUkPVBN31g3xYZFNLqTB/ZUrHTV8rRPoEElHg79L9gO3ZQWkrChvTmSOA8xZTcC3XA==,iv:U/CA9ST2IhqwL1K3/t7y0b400WNYPSCy75wM/yKFrQ4=,tag:rZx3cSanQdFy/g6uB/BdOw==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:ww9EBSlGv0S0PZz53VNs6IcZU+KdaeFXcHe/Ffo0RjFxAWmxAdxPst6shRq2Bianw/IPNwDRSfSa30qg87gYWuHR3aIr5zJC8+LkreRTZ0pL/+QalK8ehszw0jy6,iv:6u1eb+3Uq39x41jZqJLhMNlKU4NUaW1ZCRlKmqDpFik=,tag:Y/TE52GKW8Yk0OnIJM/2FA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMEliRGhWK3NWMzhqWVVn
            R0QwUU1hMVFpbStoUS9kekVidHhCVXgzN1VzCktkaWlHR3JpRUduQmx6VFVFWGMv
            S1JkKzhvUWlwMWs3MVpuUG80eU94YlUKLS0tIHJod2NURUZzMiswU0pFMnMrYUwv
            L0lGNUU2bUhWb2ZrS0F1VUhDdlN5TjAKsa2gOz1KcfEfdhkkEgBO7y7FcdN2QBCm
            9zYQl8Qq6aQLEwxAP8EwLp1OhWl5+XfgSA2Ag+4UhnPjRBWeEPWiQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-07T19:24:25Z"
    mac: ENC[AES256_GCM,data:jF7k31lgcfl7A7I8XbO+t8khOO+YtD97RwUDajSrcXzUydg7KH1wckpxLM92JEvWt+qKOC9pe9MAy//FpMat0iGmPi2rXwujPwKGj0U+WBNkxnCyon/nI9Nc+Beb4Lmdr0E9s6j84hM3yAAcKa5TcSPNlzRfy7UXcqtuFwrluWM=,iv:HDnarTcbMHrs7+/dFXjF0N67KZjyL74Qvp84Hu/t2fA=,tag:Hm8EbUjBJ5Tlods+Fo8I6Q==,type:str]
    shamir_threshold: 3
    version: 3.13.1
