apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:a+IlYg9d8muV0jijIlku3vnS3j7u0I33qRiiEyxJQKe0qcwRZF6NgZQ0PoLb9lDvgzlmTMP6ZhyBymIuMvzcwyHJmZLu3aI90mkLqYWJf/EPHz273d1nnHzdPW5KaSOv7dsERRq537V/lRf47XM1kUTwGmjA1cAlZQ==,iv:Vh2vYTx6FwhGBG7QI8eeIJmHwkhfPopo60BhgwWz9yU=,tag:79/iqGbuQfW2zrfU2lSNTQ==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:aTzrm6LhCgddnMTwp4cvXLAZoAIhwmoNwrvMchjtFRJ9EfEIqjnCw/nkVkE7rnj1Qdvf4Khp2iDx52FGP5Kafg==,iv:zizocM2phqPPvkd739tbCEpQMUt9wo4HUeiRQtS6KVA=,tag:tQ9KWF5G3ycNmMiiRU8OVg==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:Zq8nX1yydGgT0IMSBevHLsupwNHcpnHdbc+z7fvT9TvmhGlbO4nnSLwibDMv8zFCehzM7taqOED/3QUXNMRwRaoguTfl0nMQKXRt2hcIWzMvTKkJnIUXju9dn6ap,iv:yM2av9So3FgrrCbWcnDa8e/C7ImRrPzNWX5+EEXksko=,tag:yqmqTHhWx2AHctIcckx7MQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYblJlRXkrUytyT3JvaHl5
            bmxzWUdFUHpPYlYrcUduVkwweDRJT2FPT0RRCkgwR2tONm5hWDBhbHFhZkhvdGth
            d3JRdHh6QURlNTdIS3ZqbnQxWGZFQ0kKLS0tIFVVVUV5WlZ1MkFpNVVwaWdGR0Ri
            dUowL1c4c2NjKzB4dFZIZ1FZNk8wT2sKA8OwrOE9tNLJwlcWryR0kViqM6eHhUEe
            VAVW/hQtvhsyu/Dr5A5KVEnt/XfySdciZPFzEAAGHDbGLv6Slgtyxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-07T19:35:16Z"
    mac: ENC[AES256_GCM,data:0wmY+j7Rmfhir918pB9Y7mLxnjarRTCF2V1QjeDxrOAqr27Wy/Lg9myWWOn4Ezk5PkZFTfQgIQAadgxCct2nJCpRgufx/pWeH1SAhHLEUOZaaqsLbWvff6QxIAHUWt1LdxxQc1S0gMFIpMbIdBZbrnOWvbaRVGWB0CzuLuyaetk=,iv:yg0+7R2N3Oafdf4grc40KbRRtKXxrdE5YP6H0EIi2Wk=,tag:ycJJ6cy+ba9t0gcJDEbTQg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
