apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:THjuC9fcjMwSwp1oCyycyZIJCO4bh0xsk6+3wRmiB80OnzTrkqVGyXbVQewRFCKeJpuvp4+gSe4V4qrGoXgeu3YlIQ8Ho0FjAaoW3DPiS5cjt8/yQHoTNdJfsIFJGp4xepbg52AnwBMxBLKNsVGeR6tpJiCF03DAHg==,iv:HBxknqhsmtZ8Foa0qr+9OYYYWR7+ZSOUR2U8zCb3chI=,tag:3zV5zhNxORKefeVUGGz40g==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:/1ZtOG8y7vhQMCgVXWc6QDhJ2BCiKf1MZ/os0WOdkpC6cvz5EgLnm4E2QInqZAaR62U6vFRufeJrU2zRA51rkg==,iv:eL9lYlW5IwjFd7KUE/TKIPWa4bGP1rtGIcmtVuxZqDY=,tag:AcTmLsuIaTTBixrD+3Icrg==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:ah9CNcgJhjMLUO04BnMPQPVQxKgiMcJaDL/v+d1Vg8IspzFN3tGo9Cr1nMlDHuIjX+9GLqQICOCuUlT4/5yskPQ5ZyZT2MVfqB9rbS9/VYKM9UPcmQXQbjiwoLcw,iv:kV8yM0CERr2DO/kR97KTjmGxIhdeKAy5HNp7E2Kmors=,tag:7lxqCY8ps/A2tnDRQ9Ue1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdGtjcGFHVnhpRzRmQmdZ
            Y2pqUFVuTmhoaUpxWjNZdjdGS1RYSmpDaTBvCk9DZGtCeGhBWXVKOWRjeElNVG0y
            Ym8zdDFyMHhYdVhDQ1ZJalpzSjZWbHMKLS0tIFRRTU1MTkFRUDg5SlZEVzJubS9y
            MklIZEdNM0VtQUFGcEhhbDJlcE40anMK/JvWkj5j6oB+PoWUER8VjSZCv0MUcFSa
            FgAAxs6THoZ9oOi/aSJvJ7PiDRNXbEOQRcOMoTz1QOXGupFxzVgVfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-08T17:12:40Z"
    mac: ENC[AES256_GCM,data:eW7cD/gSpHMfOh3QqD66exFCUD1oOr1oO4RIUAw1t/1uSvU6JIESTGgNSbu07uBdsF8yZ6CZ+x74dMAlx4k+u1htQzghQEaSAW3G96VDicICSecZL4VbgWGdDVcBQgWkur2pB633hWDNHBqn6DnvagnGXT38of+Z9cwMzFvqKxM=,iv:NYSExudrHpcLFZBeka/VPFq7AxOv647WlWyYmDYxLzo=,tag:9qYQXe3OpGMHyfJRa0atkw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
