apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: static
    namespace: static
spec:
    interval: 15m
    chart:
        spec:
            chart: static
            version: 12.2.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Los_Angeles
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: resume.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        description: My professional resume
                        enabled: true
                        group: Utilities
                        name: Resume
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            data:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: storage
                      src:
                        enabled: true
                      type: restic
