apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - trim.yaml
  - snapshot-delete.yaml
  - snapshot-cleanup.yaml
  - storage-network-repair.yaml
  - storage-network-repair-policy.yaml

configMapGenerator:
  - name: longhorn-storage-network-repair-script
    namespace: longhorn-system
    files:
      - repair.sh=storage-network-repair.sh
