apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: matter-server
    namespace: matter-server
spec:
    interval: 15m
    chart:
        spec:
            chart: custom-app
            version: 14.2.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: matter-server
    values:
        image:
            repository: ghcr.io/home-assistant-libs/python-matter-server
            pullPolicy: IfNotPresent
            tag: stable
        TZ: America/Los_Angeles
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled

        persistence:
            config:
                enabled: true
                readOnly: false
                storageClass: ""
                targetSelector:
                    exportarr:
                        exportarr:
                            mountPath: /data
                            readOnly: true
                    main:
                        main:
                            mountPath: /data
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        ingress:
            main:
                enabled: false
        release_name: matter-server
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                loadBalancerIP: ""
                ports:
                    main:
                        enabled: true
                        port: 5580
                        protocol: http
                        targetPort: 5580
                type: LoadBalancer
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            probes:
                                liveness:
                                    enabled: true
                                    path: /
                                    type: tcp
                                readiness:
                                    enabled: true
                                    path: /
                                    type: tcp
                                startup:
                                    enabled: true
                                    path: /
                                    type: tcp
                replicas: 1
                type: Deployment
