apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: protonmail-bridge
  namespace: protonmail-bridge
spec:
  interval: 15m
  chart:
    spec:
      chart: protonmail-bridge
      version: 18.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    timeout: 30m
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Los_Angeles
    workload:
      main:
        podSpec:
          containers:
            main:
              command:
                - /bin/bash
                - -ec
              args:
                - |
                  bash /docker-entrypoint.d/99-install-fido.sh
                  exec bash /protonmail/entrypoint.sh
    credentials:
      b2:
        accessKey: ${S3_KEY_ID}
        bucket: ${S3_BUCKET}
        encrKey: ${S3_PASSWORD}
        name: b2
        secretKey: ${S3_SECRET_KEY}
        type: s3
        url: ${S3_ENDPOINT}
    persistence:
      config:
        volsync:
          - credentials: b2
            dest:
              enabled: true
            name: config
            src:
              enabled: true
            type: restic
      init-script:
        enabled: true
        type: configmap
        objectName: init-script
        mountPath: "/docker-entrypoint.d/99-install-fido.sh"
        subPath: install-fido.sh
        defaultMode: "0777"
        readOnly: true

    configmap:
      init-script:
        enabled: true
        data:
          install-fido.sh: |-
            #!/bin/bash
            echo "Installing custom packages..."
            cp /etc/skel/.* /root/
            apt-get update && apt-get install -y --no-install-recommends \
              libfido2-1
