apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: immich
    namespace: immich
spec:
    interval: 15m
    chart:
        spec:
            chart: immich
            version: 17.31.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Los_Angeles
        cnpg:
            main:
                backups:
                    credentials: b2
                    enabled: true
                    retentionPolicy: ""
                    revision: "3"
                mode: recovery
                password: ${CNPG_PASSWORD}
                pgVersion: 16
                recovery:
                    credentials: b2
                    enabled: true
                    revision: "2"
                    serverName: ""
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: pics.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: true
                        group: Apps
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            library:
                enabled: true
                path: ${IMMICH_LIBRARY_PATH}
                readOnly: false
                server: ${TRUENAS_IP}
                type: nfs
            profile:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: profiles
                      src:
                        enabled: true
                      type: restic
            thumbs:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: thumbnails
                      src:
                        enabled: true
                      type: restic
            uploads:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: uploads
                      src:
                        enabled: true
                      type: restic
            video:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: encoded-videio
                      src:
                        enabled: true
                      type: restic

