apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: ombi
    namespace: ombi
spec:
    interval: 15m
    chart:
        spec:
            chart: ombi
            version: 21.4.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Los_Angeles
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: request.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: true
                        group: Apps
                        widget:
                            custom:
                                key: ${HOMEPAGE_OMBI_KEY}
                            enabled: true
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: auth
                              namespace: "traefik"
        persistence:
            config:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
