apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: ombi
    namespace: ombi
spec:
    interval: 15m
    chart:
        spec:
            chart: ombi
            version: 19.0.9
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: ombi
    values:
        TZ: America/Los_Angeles
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: request.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        description: ""
                        enabled: true
                        group: Apps
                        icon: ""
                        name: ""
                        widget:
                            custom:
                                key: ${HOMEPAGE_OMBI_KEY}
                            enabled: true
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: auth
                              namespace: "traefik"
        mariadb:
            architecture: standalone
            auth:
                database: ombi
                password: ombi
                username: ombi
            enabled: false
            primary:
                persistence:
                    enabled: false
        persistence:
            config:
                enabled: true
                mountPath: /config
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
        release_name: ombi
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: 3579
                        targetPort: 3579
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main: {}
                replicas: 1
                type: Deployment
