apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate
  namespace: teslamate
spec:
  interval: 15m
  chart:
    spec:
      chart: teslamate
      version: 5.0.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system

  values:
    TZ: America/Los_Angeles
    cnpg:
      main:
        annotations:
          cnpg.io/skipEmptyWalArchiveCheck: "enabled"
        mode: standalone
        backups:
          enabled: true
          credentials: b2
          scheduledBackups:
            - name: daily-backup
              schedule: "30 5 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
          method: object_store
          credentials: b2
    credentials:
      b2:
        accessKey: ${S3_KEY_ID}
        bucket: ${S3_BUCKET}
        encrKey: ${S3_PASSWORD}
        name: b2
        secretKey: ${S3_SECRET_KEY}
        type: s3
        url: ${S3_ENDPOINT}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
            nginx.ingress.kubernetes.io/auth-method: 'GET'
            nginx.ingress.kubernetes.io/auth-url: http://authentik-http.authentik.svc.cluster.local:10230/outpost.goauthentik.io/auth/nginx
            nginx.ingress.kubernetes.io/auth-signin: 'https://auth.${DOMAIN_0}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri'
            nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
            nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: tesla.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
          traefik:
            enabled: false
