apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate
  namespace: teslamate
spec:
  interval: 15m
  chart:
    spec:
      chart: teslamate
      version: 5.12.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system

  values:
    TZ: America/Los_Angeles
    cnpg:
      main:
        mode: recovery
        backups:
          enabled: true
          credentials: b2
          scheduledBackups:
            - name: daily-backup
              schedule: "30 5 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
          method: object_store
          credentials: b2
    credentials:
      b2:
        accessKey: ${S3_KEY_ID}
        bucket: ${S3_BUCKET}
        encrKey: ${S3_PASSWORD}
        name: b2
        secretKey: ${S3_SECRET_KEY}
        type: s3
        url: ${S3_ENDPOINT}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: tesla.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
          nginx:
            enabled: true
            auth:
              type: "authentik"
              internalHost: "authentik-http.authentik.svc.cluster.local:10230"
              externalHost: "auth.${DOMAIN_0}"
              # Can be left default in most cases
              responseHeaders: []
