apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-helm-recovery
  namespace: longhorn-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: longhorn-helm-recovery
  namespace: longhorn-system
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - sh.helm.release.v1.longhorn.v1
    verbs:
      - get
      - delete
  - apiGroups:
      - helm.toolkit.fluxcd.io
    resources:
      - helmreleases
    resourceNames:
      - longhorn
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn-helm-recovery
  namespace: longhorn-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: longhorn-helm-recovery
subjects:
  - kind: ServiceAccount
    name: longhorn-helm-recovery
    namespace: longhorn-system
