apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - instance-manager-multus-init.yaml
  - storage-nad.yaml
components:
  - ../../../../components/notifications/discord
