apiVersion: v1
kind: Secret
metadata:
    name: reactive-resume-values
    namespace: reactive-resume
stringData:
    values.yaml: ENC[AES256_GCM,data:evtBBr1Fi+4DHjozwq00atZD9208SxsTq36GwAcyCkr3+FxKGS4i4tQcU3FaricbOEllGNG3u4MM0hLwnJy7x5wujNOtpxqw368Mmc55SJFeFPw8fOinFntg1a610wN5dSjD1pLbF69s+TNxx9UVvUBasWIaGw0rCbj5a2uGRfSoGUt776qhfGyHDstdr74UqDfEyS9qlo7C1D3S8s42UEJ4NIqqV5oGbJaSH7FagNs7o13zapdxjnZy4/uh5gcxhkrbWpRzUVLxLFPjTM/qns+Izlx+M5Pu9nlI/0djQ+Qzd9fiYS5rmNLcZZwwNswWjB3hSg3bpSqN,iv:QNN7c8u9cnVcYrB5/LH1s7gicpAYMCQ0uuXoJ4Ko5/k=,tag:qdUpJVltZ7QDVRbcYgIFbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaXYzRHRWWkZxYlMwQU1P
            MlZkSDJDSzM3bVpDOVJRQUJQUFQ3VjNVYmlzCnVHNm5oc3FYSk1icjhzZEpOalE4
            ZTIzQXhWcVNQVnVDd3k2dWVqK3lML0EKLS0tIHhTL3JJOHhxdjAveEVLL2I0MzJJ
            V2VENVJqSlR5bmlXR3Rya1MvWDNSeTQKNiIkHSxmDza8SB/PjeD21KHnzEAmkuw7
            RZan4vEFowt6sEb7Y/qdh37pgp4yvK3WqFtEsTVvDRNn1RkM/dYg+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-17T20:44:59Z"
    mac: ENC[AES256_GCM,data:caMG1Vocbk+06X0VyCY3G5QW+r10OifDRHjrSspd6ESGGG10tQcoZnoHgI1jLdOHfPBNwNghfkY6epCLsU5VzxRLWicnIm1U5HUxuZqhos7i8jQv7DcoDzlvSUJgxJZjli/gj7m99ROWLD0rpd7GWOEoUXxBZ/d1cQGXF3dNGc0=,iv:ZzPs8lnH10t6hcHLTINJXxh77JqInN2qfNFYvZG7i3I=,tag:8X9rmLBQJTQjDEjtH39zhg==,type:str]
    version: 3.13.2
