apiVersion: v1
kind: Secret
metadata:
    name: reactive-resume-values
    namespace: reactive-resume
stringData:
    values.yaml: ENC[AES256_GCM,data:WN839j7Srac2paHPmLYGQ8A1yrJLT58dOCTn0fAYXohMOd5s/tC1a0pijGXuByURI8SzYgY4o0yopGIpFhXxRzAngYDQ3++/m2IwFvDai2I+VeFv5uh42hGNusOr/YWjXQL4ipSG2v9pzJylPSFD/4h87GvQzSmycrc5DZbzO85OR562oLrlEd14rhgu65o5NoNaNptikB+N+4xe+j1MnDxJcIFWLsvb5tZBK5bTykDJJffUc4Q0ecZFtXYcI//zaRlEh3ey6edA+1miO6MEDKc/LVNVGYtLqZg8e7ULKXFD/395RZ05bTaoATynaEg+U/VHN0BwQjUA,iv:KcStoHgJXyEsBK1710msxRy2vhXLjbd+2XFctds7wtM=,tag:pPbQO/YL8iKEQk1Xb73s+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaXYzRHRWWkZxYlMwQU1P
            MlZkSDJDSzM3bVpDOVJRQUJQUFQ3VjNVYmlzCnVHNm5oc3FYSk1icjhzZEpOalE4
            ZTIzQXhWcVNQVnVDd3k2dWVqK3lML0EKLS0tIHhTL3JJOHhxdjAveEVLL2I0MzJJ
            V2VENVJqSlR5bmlXR3Rya1MvWDNSeTQKNiIkHSxmDza8SB/PjeD21KHnzEAmkuw7
            RZan4vEFowt6sEb7Y/qdh37pgp4yvK3WqFtEsTVvDRNn1RkM/dYg+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-17T20:29:52Z"
    mac: ENC[AES256_GCM,data:CoVwpSeIPsBHY+DDc1VZ2yhpMPVdKOxz1jzMmvgFR0dFHb19Bj9m85WgXDciOwzYxcuqLTIhK/h+3XrwxKportSuH3xarj4y1USSY4nc+ttO9gFKT5dyxkQpYF9USAJm3HRccDjn/6L+db801RjTK/Dgzk90sKWiKngUoKf8RbE=,iv:Tl/9DppBcx6cdNwhwTn+EntvlFXRSWINv/M/z9pNdFE=,tag:p0DMM/duUwEWN3nh8W1t9w==,type:str]
    version: 3.13.2
