apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaultwarden
    namespace: vaultwarden
spec:
    interval: 15m
    chart:
        spec:
            chart: vaultwarden
            version: 28.4.5
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Los_Angeles
        cnpg:
            main:
                backups:
                    credentials: b2
                    enabled: true
                    retentionPolicy: ""
                    revision: "3"
                mode: recovery
                password: ${CNPG_PASSWORD}
                pgVersion: 15
                recovery:
                    method: object_store
                    credentials: b2
                    enabled: true
                    revision: "2"
                    serverName: ""
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: vault.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: true
                        group: Apps
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                required: true
        persistence:
            data:
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
        vaultwarden:
            admin:
                disableAdminToken: false
                enabled: true
                token: ${ADMIN_PASSWORD}
            allowInvitation: true
            allowSignups: false
            showPasswordHint: true
            smtp:
                authMechanism: Login
                enabled: true
                from: ${ADMIN_EMAIL}
                fromName: Vaultwarden
                heloName: ""
                host: protonmail-bridge-smtp.protonmail-bridge.svc.cluster.local
                invalidCertificate: true
                invalidHostname: false
                password: ${PROTONMAIL_PASSWORD}
                port: 25
                security: starttls
                timeout: 15
                user: ${PROTONMAIL_EMAIL}
            verifySignup: true
