apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaultwarden
    namespace: vaultwarden
spec:
    interval: 15m
    chart:
        spec:
            chart: vaultwarden
            version: 27.1.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: vaultwarden
    values:
        TZ: America/Los_Angeles
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        betaImage:
            pullPolicy: IfNotPresent
            repository: ghcr.io/timshel/vaultwarden
            tag: 1.30.5-9
        cnpg:
            main:
                backups:
                    credentials: b2
                    enabled: true
                    retentionPolicy: ""
                    revision: "2"
                cluster:
                    instances: 1
                    singleNode: true
                database: vaultwarden
                enabled: true
                hibernate: false
                mode: recovery
                monitoring:
                    disableDefaultQueries: false
                    enablePodMonitor: true
                password: ${CNPG_PASSWORD}
                pgVersion: 15
                pooler:
                    enabled: false
                recovery:
                    method: object_store
                    credentials: b2
                    enabled: true
                    revision: "1"
                    serverName: ""
                user: vaultwarden
        credentials:
            b2:
                accessKey: ${S3_KEY_ID}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_PASSWORD}
                name: b2
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_ENDPOINT}
        database:
            type: postgresql
            wal: true
        ingress:
            main:
                enabled: true
                hosts:
                    - host: vault.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        description: ""
                        enabled: true
                        group: Apps
                        icon: ""
                        name: ""
                        widget:
                            custom:
                                key: ""
                            enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
                required: true
        persistence:
            data:
                enabled: true
                mountPath: /data
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: b2
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
        release_name: vaultwarden
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: 10102
                        targetPort: 8080
                type: ClusterIP
        vaultwarden:
            admin:
                disableAdminToken: false
                enabled: true
                token: ${ADMIN_PASSWORD}
            allowInvitation: true
            allowSignups: false
            attachmentLimitOrg: ""
            attachmentLimitUser: ""
            defaultInviteName: ""
            emailAttempts: 3
            emailTokenExpiration: 600
            enableWebVault: true
            hibpApiKey: ""
            icons:
                cache: 2.592e+06
                disableDownload: false
                token: 2.592e+06
            log:
                file: ""
                level: info
            orgCreationUsers: all
            push:
                enabled: false
            requireEmail: false
            showPasswordHint: true
            signupwhitelistenable: false
            smtp:
                authMechanism: Login
                enabled: true
                from: ${ADMIN_EMAIL}
                fromName: Vaultwarden
                heloName: ""
                host: protonmail-bridge-smtp.protonmail-bridge.svc.cluster.local
                invalidCertificate: true
                invalidHostname: false
                password: ${PROTONMAIL_PASSWORD}
                port: 25
                security: starttls
                timeout: 15
                user: ${PROTONMAIL_EMAIL}
            verifySignup: true
            yubico:
                enabled: false
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                DATABASE_URL:
                                    secretKeyRef:
                                        key: std
                                        name: cnpg-main-urls
                                DOMAIN: https://{{ if .Values.ingress }}{{ if .Values.ingress.main.enabled }}{{ ( index .Values.ingress.main.hosts 0 ).host }}{{ else }}placeholder.com{{ end }}{{ else }}placeholder.com{{ end }}
                            envFrom:
                                - configMapRef:
                                    name: vaultwardenconfig
                                - secretRef:
                                    name: vaultwardensecret
                            imageSelector: image
                replicas: 1
                type: Deployment
