apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: claude
  namespace: claude
spec:
  interval: 15m
  chart:
    spec:
      chart: code-server
      version: 15.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Los_Angeles
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: claude.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
          nginx:
            enabled: true
            auth:
              type: "authentik"
              internalHost: "authentik-http.authentik.svc.cluster.local:10230"
              externalHost: "auth.${DOMAIN_0}"
              # Can be left default in most cases
              responseHeaders: []
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DEFAULT_WORKSPACE: /root/workspace/
                CLAUDE_CONFIG_DIR: /root/.claude
                HOME: /root
    resources:
      limits:
        memory: 16Gi
    persistence:
      home:
        enabled: true
        mountPath: /root
        targetSelectAll: true
#--------------------------Add Claude Code---------------------------------------
      init-script:
        enabled: true
        type: configmap
        objectName: init-script
        mountPath: "/docker-entrypoint.d/99-install-claude.sh"
        subPath: install-claude.sh
        defaultMode: "0777"
        readOnly: true

    configmap:
      init-script:
        enabled: true
        data:
          install-claude.sh: |-
            #!/bin/bash
            echo "Installing claude code..."
            apt-get update && apt-get install -y --no-install-recommends \
              less \
              git-all \
              procps \
              sudo \
              fzf \
              zsh \
              man-db \
              unzip \
              gnupg2 \
              gh \
              iptables \
              ipset \
              iproute2 \
              dnsutils \
              aggregate \
              jq \
              nano \
              vim \
              nodejs \
              npm \
              ssh
            # Install kubectl
            curl -fsSL -o /usr/local/bin/kubectl \
              https://dl.k8s.io/release/$(curl -fsSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl \
              && chmod +x /usr/local/bin/kubectl
            # Install claude code
            npm install -g @anthropic-ai/claude-code@
#----------------------------------------------------------------------------------
