apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kitchenowl
  namespace: kitchenowl
spec:
  interval: 5m
  chart:
    spec:
      chart: kitchenowl
      version: 12.4.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    credentials:
      b2:
        accessKey: ${S3_KEY_ID}
        bucket: ${S3_BUCKET}
        encrKey: ${S3_PASSWORD}
        secretKey: ${S3_SECRET_KEY}
        type: s3
        url: ${S3_ENDPOINT}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: kitchen.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        volsync:
        - name: data
          type: restic
          credentials: b2
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 20 0 * * *
    cnpg:
      main:
        mode: recovery
        backups:
          enabled: true
          credentials: b2
          scheduledBackups:
            - name: daily-backup
              schedule: "0 5 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
          method: object_store
          credentials: b2
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                FRONT_URL: https://kitchen.${DOMAIN_0}
                SMTP_HOST: protonmail-bridge.protonmail-bridge.svc.cluster.local
                SMTP_PORT: 25
                SMTP_USER: ${PROTONMAIL_EMAIL}
                SMTP_PASS: ${PROTONMAIL_PASSWORD}
                SMTP_FROM: kitchenowl@${DOMAIN_0}
